stages:
  - build
  - test

variables:
  HTTP_PROXY: "http://10.61.16.6:3128"
  HTTPS_PROXY: "http://10.61.16.6:3128"
  NO_PROXY: "git.dataport.de,sonarqube.dataport.de,127.0.0.1,minio.gitlab-runner-minio.svc.cluster.local,al.s3.dataport.de,docker:2375,docker:2376,artifactory-extern.dataport.de,localhost:80"
  ARTIFACT_ROOT: "dchatbot-docker-development.artifactory-extern.dataport.de"
  IMAGE_PATH: "/conplat/cci/endtoendtests"
  CONTAINER_NAME: "cci-frontend"
  TAG_LATEST: $CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  TAGNAME: ccie2e
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_URL: "docker.artifactory-extern.dataport.de"

buildJob:
  image: tmaier/docker-compose:latest
  stage: build
  script:
    - docker login -u $CONPLAT_ARTIFACTORY_USER -p $CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT
    - docker push $ARTIFACT_ROOT$IMAGE_PATH 
  only:
    - merge_requests
  
testJob1:
  image: tmaier/docker-compose:latest
  stage: test
  script:
    - ifconfig lo:0 172.14.1.1 up
    - docker login -u $CONPLAT_ARTIFACTORY_USER -p $CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT
    - docker-compose up -d --build
    - sleep 10

  artifacts:
    paths:
      - ./public

testJob2:
  image: akash062/cci:$TAGNAME
  stage: test
  script:
    - npm install xvfb
    - npm install cypress
    - npm install
    - npm run cypress:run